const insertion = [
  {
    year: 2022,
    country: "Bahrain",
    city: "Sakhir",
    standings: [
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Albon", team: "Williams" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Hulkenberg", team: "Aston Martin" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Latifi", team: "Williams" },
    ],
    poleLap: 90558,
  },
  {
    year: 2022,
    country: "Saudi Arabia",
    city: "Jeddah",
    standings: [
      { driver: "Perez", team: "Red Bull" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Albon", team: "Williams" },
      { driver: "Hulkenberg", team: "Aston Martin" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
    ],
    poleLap: 88200,
  },
  {
    year: 2022,
    country: "Australia",
    city: "Melbourne",
    standings: [
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Albon", team: "Williams" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Stroll", team: "Aston Martin" },
    ],
    poleLap: 77868,
  },
  {
    year: 2022,
    country: "Italy",
    city: "Imola",
    standings: [
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Albon", team: "Williams" },
    ],
    poleLap: 87999,
  },
  {
    year: 2022,
    country: "United States",
    city: "Miami",
    standings: [
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Albon", team: "Williams" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Ocon", team: "Alpine" },
    ],
    poleLap: 88796,
  },
  {
    year: 2022,
    country: "Spain",
    city: "Barcelona",
    standings: [
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Albon", team: "Williams" },
      { driver: "Latifi", team: "Williams" },
    ],
    poleLap: 78750,
  },
  {
    year: 2022,
    country: "Monaco",
    city: "Monaco",
    standings: [
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Albon", team: "Williams" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Zhou", team: "Alfa Romeo" },
    ],
    poleLap: 71376,
  },
  {
    year: 2022,
    country: "Azerbaijan",
    city: "Baku",
    standings: [
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Albon", team: "Williams" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Schumacher", team: "Haas" },
    ],
    poleLap: 101359,
  },
  {
    year: 2022,
    country: "Canada",
    city: "Montreal",
    standings: [
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Albon", team: "Williams" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
    ],
    poleLap: 81299,
  },
  {
    year: 2022,
    country: "Great Britain",
    city: "Silverstone",
    standings: [
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Albon", team: "Williams" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Stroll", team: "Aston Martin" },
    ],
    poleLap: 100983,
  },
  {
    year: 2022,
    country: "Austria",
    city: "Spielberg",
    standings: [
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Albon", team: "Williams" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Vettel", team: "Aston Martin" },
    ],
    poleLap: 64984,
  },
  {
    year: 2022,
    country: "France",
    city: "Le Castellet",
    standings: [
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Albon", team: "Williams" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Latifi", team: "Williams" },
    ],
    poleLap: 90872,
  },
  {
    year: 2022,
    country: "Hungary",
    city: "Budapest",
    standings: [
      { driver: "Russell", team: "Mercedes" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Albon", team: "Williams" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Latifi", team: "Williams" },
    ],
    poleLap: 77377,
  },
  {
    year: 2022,
    country: "Belgium",
    city: "Spa-Francorchamps",
    standings: [
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Albon", team: "Williams" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Bottas", team: "Alfa Romeo" },
    ],
    poleLap: 103665,
  },
  {
    year: 2022,
    country: "Netherlands",
    city: "Zandvoort",
    standings: [
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Albon", team: "Williams" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Latifi", team: "Williams" },
    ],
    poleLap: 70342,
  },
  {
    year: 2022,
    country: "Italy",
    city: "Monza",
    standings: [
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "De Vries", team: "Williams" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Schumacher", team: "Haas" },
    ],
    poleLap: 80161,
  },
  {
    year: 2022,
    country: "Singapore",
    city: "Singapore",
    standings: [
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Albon", team: "Williams" },
      { driver: "Latifi", team: "Williams" },
    ],
    poleLap: 109412,
  },
  {
    year: 2022,
    country: "Japan",
    city: "Suzuka",
    standings: [
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Albon", team: "Williams" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Latifi", team: "Williams" },
    ],
    poleLap: 89304,
  },
  {
    year: 2022,
    country: "United States",
    city: "Austin",
    standings: [
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Albon", team: "Williams" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Latifi", team: "Williams" },
    ],
    poleLap: 94356,
  },
  {
    year: 2022,
    country: "Mexico",
    city: "Mexico City",
    standings: [
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Albon", team: "Williams" },
      { driver: "Latifi", team: "Williams" },
    ],
    poleLap: 77775,
  },
  {
    year: 2022,
    country: "Brazil",
    city: "Sao Paulo",
    standings: [
      { driver: "Magnussen", team: "Haas" },
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Albon", team: "Williams" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Schumacher", team: "Haas" },
    ],
    poleLap: 71674,
  },
  {
    year: 2022,
    country: "United Arab Emirates",
    city: "Abu Dhabi",
    standings: [
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Albon", team: "Williams" },
      { driver: "Latifi", team: "Williams" },
    ],
    poleLap: 83824,
  },
];

module.exports = insertion;
