const insertion = [
  {
    year: 2021,
    country: "Italy",
    city: "Monza",
    standings: [
      "Verstappen",
      "Leclerc",
      "Hamilton",
      "Ocon",
      "Alonso",
      "Bottas",
    ],
    fastestLap: 79,
  },
  {
    year: 2021,
    country: "France",
    city: "Le Castellet",
    standings: [
      "Leclerc",
      "Hamilton",
      "Ocon",
      "Verstappen",
      "Alonso",
      "Bottas",
    ],
    fastestLap: 90,
  },
  {
    year: 2021,
    country: "Azerbaijan",
    city: "Baku",
    standings: [
      "Ocon",
      "Hamilton",
      "Bottas",
      "Leclerc",
      "Alonso",
      "Verstappen",
    ],
    fastestLap: 96,
  },
  {
    year: 2021,
    country: "Great Britain",
    city: "Silverstone",
    standings: [
      "Leclerc",
      "Verstappen",
      "Alonso",
      "Hamilton",
      "Bottas",
      "Ocon",
    ],
    fastestLap: 86,
  },
  {
    year: 2021,
    country: "Hungary",
    city: "Budapest",
    standings: [
      "Verstappen",
      "Hamilton",
      "Alonso",
      "Leclerc",
      "Ocon",
      "Bottas",
    ],
    fastestLap: 71,
  },
  {
    year: 2020,
    country: "Italy",
    city: "Imola",
    standings: [
      "Ocon",
      "Hamilton",
      "Verstappen",
      "Alonso",
      "Leclerc",
      "Bottas",
    ],
    fastestLap: 78,
  },
  {
    year: 2020,
    country: "Spain",
    city: "Barcelona",
    standings: [
      "Hamilton",
      "Ocon",
      "Alonso",
      "Verstappen",
      "Leclerc",
      "Bottas",
    ],
    fastestLap: 82,
  },
  {
    year: 2020,
    country: "Autria",
    city: "Spielberg",
    standings: [
      "Hamilton",
      "Alonso",
      "Leclerc",
      "Verstappen",
      "Bottas",
      "Ocon",
    ],
    fastestLap: 69,
  },
  {
    year: 2020,
    country: "Germany",
    city: "Hockenheim",
    standings: [
      "Alonso",
      "Ocon",
      "Hamilton",
      "Leclerc",
      "Verstappen",
      "Bottas",
    ],
    fastestLap: 75,
  },
  {
    year: 2020,
    country: "Australia",
    city: "Melbourne",
    standings: [
      "Bottas",
      "Alonso",
      "Ocon",
      "Leclerc",
      "Verstappen",
      "Hamilton",
    ],
    fastestLap: 82,
  },
];

module.exports = insertion;
