const insertion = [
  {
    year: 2022,
    country: "Barhain",
    city: "Sakhir",
    standings: [
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Albon", team: "Williams" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Hulkenberg", team: "Aston Martin" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Gasly", team: "Alpha Tauri" },
    ],
    duration: 5853584,
    lapsCompleted: 57,
  },
  {
    year: 2022,
    country: "Saudi Arabia",
    city: "Jeddah",
    standings: [
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Hulkenberg", team: "Aston Martin" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Albon", team: "Williams" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Schumacher", team: "Haas" },
    ],
    duration: 5059293,
    lapsCompleted: 50,
  },
  {
    year: 2022,
    country: "Australia",
    city: "Melbourne",
    standings: [
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Albon", team: "Williams" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Sainz", team: "Ferrari" },
    ],
    duration: 5266548,
    lapsCompleted: 58,
  },
  {
    year: 2022,
    country: "Italy",
    city: "Imola",
    standings: [
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Albon", team: "Williams" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Sainz", team: "Ferrari" },
    ],
    duration: 5527986,
    lapsCompleted: 63,
  },
  {
    year: 2022,
    country: "United States",
    city: "Miami",
    standings: [
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Albon", team: "Williams" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Zhou", team: "Alfa Romeo" },
    ],
    duration: 5664258,
    lapsCompleted: 57,
  },
  {
    year: 2022,
    country: "Spain",
    city: "Barcelona",
    standings: [
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Albon", team: "Williams" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Leclerc", team: "Ferrari" },
    ],
    duration: 5840475,
    lapsCompleted: 66,
  },
  {
    year: 2022,
    country: "Monaco",
    city: "Monaco",
    standings: [
      { driver: "Perez", team: "Red Bull" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Albon", team: "Williams" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Magnussen", team: "Haas" },
    ],
    duration: 6990265,
    lapsCompleted: 64,
  },
  {
    year: 2022,
    country: "Azerbaijan",
    city: "Baku",
    standings: [
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Albon", team: "Williams" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Sainz", team: "Ferrari" },
    ],
    duration: 5645941,
    lapsCompleted: 51,
  },
  {
    year: 2022,
    country: "Canada",
    city: "Montreal",
    standings: [
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Albon", team: "Williams" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Perez", team: "Red Bull" },
    ],
    duration: 5781757,
    lapsCompleted: 70,
  },
  {
    year: 2022,
    country: "Great Britain",
    city: "Silverstone",
    standings: [
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Albon", team: "Williams" },
    ],
    duration: 8270311,
    lapsCompleted: 52,
  },
  {
    year: 2022,
    country: "Austria",
    city: "Spielberg",
    standings: [
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Albon", team: "Williams" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Perez", team: "Red Bull" },
    ],
    duration: 5064312,
    lapsCompleted: 71,
  },
  {
    year: 2022,
    country: "France",
    city: "Le Castellet",
    standings: [
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Albon", team: "Williams" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
    ],
    duration: 5402112,
    lapsCompleted: 53,
  },
  {
    year: 2022,
    country: "Hongrie",
    city: "Budapest",
    standings: [
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Albon", team: "Williams" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Bottas", team: "Alfa Romeo" },
    ],
    duration: 5975912,
    lapsCompleted: 70,
  },
  {
    year: 2022,
    country: "Belgium",
    city: "Spa-Francorchamps",
    standings: [
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Albon", team: "Williams" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Hamilton", team: "Mercedes" },
    ],
    duration: 5152894,
    lapsCompleted: 44,
  },
  {
    year: 2022,
    country: "Netherlands",
    city: "Zandvoort",
    standings: [
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Albon", team: "Williams" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
    ],
    duration: 5802773,
    lapsCompleted: 72,
  },
  {
    year: 2022,
    country: "Italy",
    city: "Monza",
    standings: [
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "De Vries", team: "Williams" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Vettel", team: "Aston Martin" },
    ],
    duration: 4827511,
    lapsCompleted: 53,
  },
  {
    year: 2022,
    country: "Singapore",
    city: "Singapore",
    standings: [
      { driver: "Perez", team: "Red Bull" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Albon", team: "Williams" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Zhou", team: "Alfa Romeo" },
    ],
    duration: 7340238,
    lapsCompleted: 59,
  },
  {
    year: 2022,
    country: "Japan",
    city: "Suzuka",
    standings: [
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Albon", team: "Williams" },
    ],
    duration: 10904004,
    lapsCompleted: 28,
  },
  {
    year: 2022,
    country: "United States",
    city: "Austin",
    standings: [
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Albon", team: "Williams" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Sainz", team: "Ferrari" },
    ],
    duration: 6131687,
    lapsCompleted: 56,
  },
  {
    year: 2022,
    country: "Mexico",
    city: "Mexico City",
    standings: [
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Albon", team: "Williams" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
    ],
    duration: 5916729,
    lapsCompleted: 71,
  },
  {
    year: 2022,
    country: "Brazil",
    city: "Sao Paulo",
    standings: [
      { driver: "Russell", team: "Mercedes" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Albon", team: "Williams" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Ricciardo", team: "McLaren" },
    ],
    duration: 5914044,
    lapsCompleted: 71,
  },
  {
    year: 2022,
    country: "United Arab Emirates",
    city: "Abu Dhabi",
    standings: [
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Albon", team: "Williams" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Alonso", team: "Alpine" },
    ],
    duration: 5265914,
    lapsCompleted: 58,
  },
];

module.exports = insertion;
