const insertion = [
  {
    year: 2022,
    country: "Italy",
    city: "Imola",
    standings: [
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Albon", team: "Williams" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Zhou", team: "Alfa Romeo" },
    ],
    duration: 1839567,
  },
  {
    year: 2022,
    country: "Austria",
    city: "Spielberg",
    standings: [
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Russell", team: "Mercedes" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Albon", team: "Williams" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Alonso", team: "Alpine" },
    ],
    duration: 1590059,
  },
  {
    year: 2022,
    country: "Brazil",
    city: "Sao Paulo",
    standings: [
      { driver: "Russell", team: "Mercedes" },
      { driver: "Sainz", team: "Ferrari" },
      { driver: "Hamilton", team: "Mercedes" },
      { driver: "Verstappen", team: "Red Bull" },
      { driver: "Perez", team: "Red Bull" },
      { driver: "Leclerc", team: "Ferrari" },
      { driver: "Norris", team: "McLaren" },
      { driver: "Magnussen", team: "Haas" },
      { driver: "Vettel", team: "Aston Martin" },
      { driver: "Gasly", team: "Alpha Tauri" },
      { driver: "Ricciardo", team: "McLaren" },
      { driver: "Schumacher", team: "Haas" },
      { driver: "Zhou", team: "Alfa Romeo" },
      { driver: "Bottas", team: "Alfa Romeo" },
      { driver: "Tsunoda", team: "Alpha Tauri" },
      { driver: "Stroll", team: "Aston Martin" },
      { driver: "Ocon", team: "Alpine" },
      { driver: "Alonso", team: "Alpine" },
      { driver: "Latifi", team: "Williams" },
      { driver: "Albon", team: "Williams" },
    ],
    duration: 1811307,
  },
];